# 1. NumPy 入门


In [9]:
import time # 导入 time 模块
import numpy as np

In [12]:
# 需求：计算100万个数字的平方和（NumPy数组 与 Python 原生列表的速度对比）

# Python原生列表
# li = []
# for i in range(1,100001):
#     li.append(i)
# print(li)
# 开始时间记录
start_time = time.time()

# 列表表达式
li = [i for i in range(1,100001)]
print(sum(li))

# 耗时
print(f"Python 列表耗时：{time.time() - start_time}秒")

# NumPy 数组
start_time1 = time.time()
print(np.sum(np.arange(100001)))
print(f"NumPy 数组耗时：{time.time() - start_time1}秒")

# 得出两个时间的差值
time_diff = time.time() - start_time1 - (time.time() - start_time)
print(f"NumPy 数组比 Python 列表快：{time_diff}秒")


5000050000
Python 列表耗时：0.00865793228149414秒
5000050000
NumPy 数组耗时：0.0008766651153564453秒
NumPy 数组比 Python 列表快：-0.008723020553588867秒


In [15]:
# 验证 NumPy版本
print(f"NumPy版本为：{np.__version__}")


NumPy版本为：2.5.2


# 2. NumPy 数据类型
## dtype 定义数组元素的类型
 - 直接指定类型：np.dtype(类型名)
 - 定义结构化类型：用于存储多字段数据（如“姓名 + 年龄 + 成绩”的学生信息）

**注意： **缺失值 np.nan 只能存在于float类型，整数数组不能存储缺失值，强行存储会报错

In [16]:
# 查看基础 dtype 对象

# 查看 int64 类型的 dtype 对象
int_dtype = np.dtype(np.int64)
print("int64 的 dtype 对象", int_dtype)
print("数据类型名称：", int_dtype.name)
print("字节数：",int_dtype.itemsize)

int64 的 dtype 对象 int64
数据类型名称： int64
字节数： 8


In [21]:
# 创建数组时dtype
arr = np.array([1.8,2.9,3.45],dtype = np.float64)
print(arr)
print(arr.dtype) # 浮点数转整数会丢失小数部分

[1.8  2.9  3.45]
float64


In [27]:
arr_int = np.array([1,2,np.nan])
print(arr_int)
print(arr_int.dtype)


[ 1.  2. nan]
float64


In [32]:
# 创建结构化的 dtype 对象（存多字段数据，如学生成绩）
# 字段名（score）+ 类型（int8，用标识码“11”表示）
score_dtype = np.dtype([('name','U10'),('score','i1')])
print("结构化：",score_dtype)

# 用结构化 dtype 创建数组
score_arr = np.array([('Alice',100),('Bob',90),('Charlie',80)],dtype = score_dtype)
print(score_arr)
print(score_arr['score'])


结构化： [('name', '<U10'), ('score', 'i1')]
[('Alice', 100) ('Bob',  90) ('Charlie',  80)]
[100  90  80]


In [36]:
arr1 = np.array([1.3,1.4,5.4],dtype = 'f4')
print(arr1)
print(arr1.dtype)

[1.3 1.4 5.4]
float32


In [38]:
# 原数组(int64 类型)
arr_int = np.array([1,2,3,4,5])
print(arr_int)
print(arr_int.dtype)


[1 2 3 4 5]
int64


In [39]:
# 转换为 float64 类型（高精度）
arr_int = arr_int.astype(np.float64)
print(arr_int)
print(arr_int.dtype)

[1. 2. 3. 4. 5.]
float64


In [40]:
# 转换为 uint8 类型
arr_int = arr_int.astype(np.uint8)
print(arr_int)
print(arr_int.dtype)

[1 2 3 4 5]
uint8


In [42]:
# 转换为字符串类型
arr_int = arr_int.astype(np.str_)
print(arr_int)
print(arr_int.dtype)

['1' '2' '3' '4' '5']
<U3


In [43]:
# 注意：高精度转低精度可能会丢失数据
arr_int = np.array([1,2,3,4,5])
arr_int = arr_int.astype(np.float64)
arr_int = arr_int.astype(np.uint8)
arr_int = arr_int.astype(np.str_)
print(arr_int)
print(arr_int.dtype)

['1' '2' '3' '4' '5']
<U3


In [45]:
# 创建不同维度的数组
# 0维数组（标量）
n = 1

# 1维数组（向量）
arr11 = np.array([1,2,3,4,5])

# 2维数组（矩阵）
arr12 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# 3维数组
arr13 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr11,arr12,arr13,end="\n\n")

[1 2 3 4 5] [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [46]:
# 同质性
arr = np.array([1,"hello"])
print(arr)
print(arr.dtype) # 自动向上转换

['1' 'hello']
<U21


In [47]:
# 强制指定最小维度
arr3 = np.array([10,20,30],ndmin=2)
print(arr3)

[[10 20 30]]


# 3. 创建特殊数组（实用技巧）
针对“全 0 数组”“全 1 数组”“单位矩阵”等常见场景，NumPy 提供了专门的函数，无需手动构造列表，效率更高。

In [50]:
# np.zeros(shape, dtype=float, order="C")  创建全 0 数组
# 关键参数 shape：数组形状
z = np.zeros((2, 3))        # 2 行 3 列全 0 数组
print(z)
print('dtype =', z.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
dtype = float64


In [51]:
# np.ones(shape, dtype=float, order="C")  创建全 1 数组
# 关键参数同 np.zeros()
o = np.ones((3, 4), dtype=int)   # 3 行 4 列整型全 1 数组
print(o)
print('dtype =', o.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
dtype = int64


In [52]:
# np.empty(shape, dtype=float, order="C")  创建未初始化数组
# 关键参数同 np.zeros()；值为内存残留，看似随机
e = np.empty((2, 2))        # 2 行 2 列未初始化数组
print(e)

[[1. 1.]
 [1. 1.]]


In [53]:
# np.full(shape, fill_value)  创建固定值数组
# 关键参数 fill_value：数组元素的固定值
f = np.full((2, 3), 666)    # 2 行 3 列全为 666 的数组
print(f)

[[666 666 666]
 [666 666 666]]


In [54]:
# np.eye(n, m=None)  创建单位矩阵（对角线为 1，其余为 0）
# 关键参数 n：行数；m：列数（默认等于 n）
i3 = np.eye(3)              # 3 阶单位矩阵
print(i3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**提示：** 嵌套几层列表，就是几维数组！创建时尽量不要混存不同类型（比如整数+字符串），会影响计算！

In [55]:
# 2行3列的全0数组
zeros_arr = np.zeros((2,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
# 创建1维0数组
zeros_arr2 = np.zeros((10,),dtype=np.int32)
print(zeros_arr2)

[0 0 0 0 0 0 0 0 0 0]


In [58]:
# 使用自定义的数据类型创建全0数组
print(np.zeros((2,3),dtype=[('x','i4'),('y','i4')]))

[[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]


In [59]:
# 全1数组
# 5行8列的全1数组
ones_arr = np.ones((5,8),dtype=int)
print(ones_arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [60]:
# 未初始化数组（元素随机值）
empty_arr = np.empty((2,3))
print(empty_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
# 固定值数组
full_arr = np.full((3,4),2025)
print(full_arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [62]:
# 拓展：基于已有的数组形状创建特殊数据
# xxx_link() 系列函数

# 先定义一个参考函数
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)


[[1 2]
 [3 4]
 [5 6]]


In [63]:
# 创建与 arr 形状相同的全0数组
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

[[0 0]
 [0 0]
 [0 0]]


In [64]:
# 创建与 arr 形状相同的未初始化数组
empty_like_arr = np.empty_like(arr)
print(empty_like_arr)

[[0 0]
 [0 0]
 [0 0]]


In [65]:
# 创建与 arr 形状相同的固定值数组
full_like_arr = np.full_like(arr,2026)
print(full_like_arr)

[[2026 2026]
 [2026 2026]
 [2026 2026]]
